---
include:
  - board: nice_nano_v2
    shield: corne_left
    cmake-args: -DSHIELD="nice_view_adapter nice_view"
    artifact-name: corne_left_with_view_adapter
  - board: nice_nano_v2
    shield: corne_right
    cmake-args: -DSHIELD="nice_view_adapter nice_view"
    artifact-name: corne_right_with_view_adapter
  - board: nice_nano_v2
    shield: reviung41
    artifact-name: reviung41_firmware
