name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      board: nice_nano_v2
      shield: corne_left
      build-name: corne_left_build
    env:
      ZMK_CONFIG: /tmp/zmk-config/config
      SHIELD: "corne_left nice_view_adapter nice_view"
      ZMK_EXTRA_MODULES: /__w/Chocofi-Qwerty/Chocofi-Qwerty
